/**
 * @description       : 
 * @author            :  Shiva Rajendran Viji
 * @group             : 
 * @last modified on  : 03-26-2025
 * @last modified by  : Shiva Rajendran Viji
**/
public class HelloWorld {
    public static void hello() {
        System.debug('Hello from DF18!! Updated3'+ System.now());
        System.debug('1');

    }

    public integer add(integer a, integer b) {
        return a + b;

    }
}