/**
 * @description       : 
 * @author            :  Shiva Rajendran Viji
 * @group             : 
 * @last modified on  : 04-01-2025
 * @last modified by  : Shiva Rajendran Viji
**/
public class HelloWorld {
    public static void hello() {
        System.debug('Hello from DF18!! Updated3'+ System.now());
        System.debug('2 ' + 'date today is 4-1-205');

    }

    public static integer addNumb(integer a, integer b) {
        return a + b;

    }
}